# Generated by Django 4.0 on 2021-12-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayslog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayslog',
            name='happenings',
            field=models.TextField(default='<h1>Things that happened today</h1>\n<ol>\n  <li>Clock ticked over midnight.</li>\n</ol>'),
        ),
        migrations.AlterField(
            model_name='dayslog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
